sonar.projectKey=blog-pessoal-dotnet
sonar.working.directory=D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal
sonar.pullrequest.cache.basepath=D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal

20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.projectKey=blog-pessoal-dotnet:20B98393-43A4-E386-15FF-47545BD6C5B5
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.projectName=BlogPessoal
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.projectBaseDir=D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.sourceEncoding=utf-8
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.tests=
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.sources=\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Controllers\\PostagensController.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Controllers\\TemasController.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Controllers\\UsuariosController.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Data\\BlogDbContext.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Mappings\\PostagemDTOMappingExtensions.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Mappings\\TemaDTOMappingExtensions.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Mappings\\UsuarioDTOMappingExtensions.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Postagens\\PostagemRequestDTO.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Postagens\\PostagemResponseDTO.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Postagens\\PostagemUpdateDTO.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Status\\Response.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Temas\\TemaRequestDTO.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Temas\\TemaResponseDTO.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Temas\\TemaUpdateDTO.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Usuarios\\UsuarioRequestDTO.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Usuarios\\UsuarioResponseDTO.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\DTOs\\Usuarios\\UsuarioUpdateDTO.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Middlewares\\Exceptions\\ApiExceptionMiddlewareExtensions.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Middlewares\\Exceptions\\ErrorDetails.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Middlewares\\Filters\\ApiExceptionFilter.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Middlewares\\Filters\\ApiLoggingFilter.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Migrations\\20260518233607_BancoInicial.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Migrations\\20260518233607_BancoInicial.Designer.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Migrations\\20260519135456_RetirandoNome.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Migrations\\20260519135456_RetirandoNome.Designer.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Migrations\\BlogDbContextModelSnapshot.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Models\\Pagination\\PagedList.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Models\\Pagination\\PostagensFiltroAutorTema.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Models\\Pagination\\QueryStringParameters.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Models\\Postagem.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Models\\Tema.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Models\\Usuario.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Models\\UsuarioLogin.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Program.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Repositories\\GenericRepository\\IRepository.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Repositories\\GenericRepository\\Repository.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Repositories\\Postagens\\IPostagemRepository.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Repositories\\Postagens\\PostagemRepository.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Repositories\\Temas\\ITemaRepository.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Repositories\\Temas\\TemaRepository.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Repositories\\UnitsOfWork\\IUnitOfWork.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Repositories\\UnitsOfWork\\UnitOfWork.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Services\\Token\\ITokenService.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Services\\Token\\TokenService.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Services\\Usuario\\IUsuariosServices.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Services\\Usuario\\UsuariosServices.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\BlogPessoal.GlobalUsings.g.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\BlogPessoal.AssemblyInfo.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\BlogPessoal.MvcApplicationPartsAssemblyInfo.cs",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\appsettings.Development.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\appsettings.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\BlogPessoal.http",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\Properties\\launchSettings.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\BlogPessoal.csproj.nuget.dgspec.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\project.assets.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\.vs\\BlogPessoal.slnx\\v18\\DocumentLayout.backup.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\.vs\\BlogPessoal.slnx\\v18\\DocumentLayout.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\appsettings.Development.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\appsettings.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\BlogPessoal.deps.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\BlogPessoal.runtimeconfig.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\bin\\Debug\\net10.0\\BlogPessoal.staticwebassets.endpoints.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\ApiEndpoints.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\BlogPessoal.sourcelink.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\rjsmcshtml.dswa.cache.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\rjsmrazor.dswa.cache.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\rpswa.dswa.cache.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\staticwebassets.build.endpoints.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\staticwebassets.build.json",\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\obj\\Debug\\net10.0\\EndpointInfo\\BlogPessoal.json"

20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.cs.analyzer.projectOutPaths=\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\0"
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.cs.roslyn.reportFilePaths=\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\0\\Issues.json"
20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.cs.scanner.telemetry=\
"D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\0\\Telemetry.json"

20B98393-43A4-E386-15FF-47545BD6C5B5.sonar.working.directory=D:\\AceleraMaker\\projetosAceleraMaker\\Projeto semanas 3 e 4 - Blog Pessoal\\BlogPessoal\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=20B98393-43A4-E386-15FF-47545BD6C5B5

